name: Build and Release Halo Firmware

env:
  DEVICE_NAME: halo
  RELEASE_URL: ${{ github.server_url }}/${{ github.repository }}/releases/latest

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        description: 'The version of the firmware to build'
        required: true
  release:
    types: [published]

jobs:
  build-firmware:
    name: Build And Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.7

      - name: Build ESPHome Firmware
        uses: esphome/workflows/.github/workflows/build.yml@main
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          files: |
            TFT_LCD/T-Display-Long/V1/Firmware/ESPHome/Halo-v1.yaml
          esphome-version: stable
          combined-name: firmware
          release-summary: ${{ github.event.release.body || '' }}
          release-url: ${{ github.event.release.html_url || '' }}
          release-version: ${{ github.event.release.tag_name || inputs.version || 'dev' }}

      - name: Upload Firmware Artifact
        uses: actions/upload-artifact@v4.3.6
        with:
          name: firmware
          path: firmware

  build-site:
    name: Build Site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4.1.7

      - name: Build Site
        uses: actions/jekyll-build-pages@v1.0.13
        with:
          source: ./static
          destination: ./output

      - name: Upload Site Artifact
        uses: actions/upload-artifact@v4.3.6
        with:
          name: site
          path: output

  publish:
    name: Publish to GitHub Pages
    runs-on: ubuntu-latest
    needs:
      - build-firmware
      - build-site
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download Firmware Artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: firmware
          path: firmware

      - name: Copy Firmware and Manifest
        run: |
          mkdir -p output/firmware
          cp -r firmware/* output/firmware/

      - name: Download Site Artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: site
          path: output

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: output
          retention-days: 1

      - name: Setup Pages
        uses: actions/configure-pages@v5.0.0

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
